---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify Splunk Universal Forwarder
      ansible.builtin.command: which splunk
      changed_when: false
      register: result
      failed_when: result.rc != 0

    - name: Verify osquery
      ansible.builtin.command: which osqueryd
      changed_when: false
      register: result
      failed_when: result.rc != 0

    - name: Verify osqueryd service exists
      ansible.builtin.stat:
        path: /etc/systemd/system/osqueryd.service
      register: result
      failed_when: not result.stat.exists

    - name: Verify auditd
      ansible.builtin.command: which auditd
      changed_when: false
      register: result
      failed_when: result.rc != 0

    - name: Verify Sysmon Linux exists
      ansible.builtin.stat:
        path: /opt/sysmon/SysmonLinux
      register: result
      failed_when: not result.stat.exists

    - name: Verify ART directory exists
      ansible.builtin.stat:
        path: /opt/art
      register: result
      failed_when: not result.stat.isdir
